<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PcRemote.Modules.SystemInfo</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PcRemote.Core\PcRemote.Core.csproj" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.12" />
    <PackageReference Include="System.Management" Version="10.0.12" />
  </ItemGroup>
</Project>
