<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PcRemote.Modules.Terminal</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PcRemote.Core\PcRemote.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="PcRemote.Tests" />
  </ItemGroup>
</Project>
